name: build-mac

on:
  workflow_dispatch:
  push:

jobs:
  build-mac:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        target: [
            # llvm11, llvm12, llvm13, llvm14, wasm32,
            cross-aarch64-darwin,
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-22.11

      - name: Build barretenberg on ${{ matrix.target }}
        run: |
          nix build -L .#${{ matrix.target }}

      - name: Prepare artifacts
        run: |
          mkdir artifacts
          cp -a ./result/. artifacts

      - name: Upload ${{ matrix.target }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ./artifacts/
          retention-days: 3

  bb_wrapper:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-22.11

      - name: Build barretenberg_wrapper
        working-directory: ./barretenberg_wrapper
        # This removes the lockfile as a workaround to relative file paths causing a failure in flakes
        run: |
          rm flake.lock
          nix build -L
          ./result/bin/barretenberg_wrapper
